### ISSUE TITLE
HTTPS fails

### ISSUE THREAD

**Issue by 44trent3** [madd-games/maddcraft#1]
Today, I was trying to use the launcher. However, whenever I tried to download a version, it failed to download, due to it failing to establish an SSL connection, both to s3.amazonaws.com and libraries.minecraft.net. I fixed this by changing all instances of "https" to normal http. So I figured out the issue, but this is an issue nonetheless.

**Comment by madd-games** [comment]
on what operating system? and what version of python?

**Comment by 44trent3** [comment]
It turns out it was on my end, my SSL certificates were screwed up.

**Comment by 44trent3** [comment]
Don't know where else to put this, but sorry about that miscommunication, I was being stupid about it.
