### ISSUE TITLE
Doesn't work in Python 3

### ISSUE THREAD

**Issue by 44trent3** [madd-games/maddcraft#2]
Don't know if this is intentional or not, but this does _not_  work with Python 3.

**Comment by madd-games** [comment]
Indeed, i do not know much about python 3 so i have not ported it. You can fix the problem yourself (ensuring that it continues to work with python 2) and submit a pull request if you want.

Otherwise, show the error youre getting so that i may look into it

**Comment by madd-games** [comment]
it appears that i won't get any response on this
